[package]
name = "argonfand"
version = "0.1.0"
authors = ["Adrian Wo≈∫niak <adrian.wozniak.1986@gmail.com>"]
edition = "2018"

[dependencies]
rppal = { version = "0.11.3" }
gpio = { version = "0.4.1" }
gumdrop = { version = "0.8.0" }
